spring.application.name=eindopdracht-backend-api

spring.datasource.url=jdbc:postgresql://localhost:5432/eindopdracht-backend-api
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

client-id=eindopdracht-backend-api
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/eindopdracht-api
spring.security.oauth2.resourceserver.jwt.audiences=eindopdracht-backend-api

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB